import React, { useState, useEffect } from 'react';
import { Download, X } from 'lucide-react';

export const InstallButton = () => {
    const [deferredPrompt, setDeferredPrompt] = useState<any>(null);
    const [isIOS, setIsIOS] = useState(false);
    const [showIOSPrompt, setShowIOSPrompt] = useState(false);
    const [debugStatus, setDebugStatus] = useState("Initializing...");
    const [swStatus, setSwStatus] = useState("Checking...");

    const registerSW = async () => {
        if ('serviceWorker' in navigator) {
            try {
                // Try to register explicitly (Vite PWA usually does this, but we force it for debug)
                // The sw.js file is generated by vite-plugin-pwa at the root
                const reg = await navigator.serviceWorker.register('/sw.js', { scope: '/' });
                setSwStatus(`Registered (${reg.scope})`);
                // console.log('SW Registered:', reg);
            } catch (err: any) {
                setSwStatus(`Error: ${err.message}`);
                console.error('SW Error:', err);
            }
        } else {
            setSwStatus("Not Supported");
        }
    };

    useEffect(() => {
        const handler = (e: any) => {
            e.preventDefault();
            setDeferredPrompt(e);
            setDebugStatus("Ready to Install");
        };
        window.addEventListener('beforeinstallprompt', handler);

        const ios = /iPad|iPhone|iPod/.test(navigator.userAgent) && !(window as any).MSStream;
        setIsIOS(ios);
        if (ios) setDebugStatus("iOS Device Detected");
        else if (!deferredPrompt) setDebugStatus("Waiting for Prompt...");

        // Check Service Worker
        if ('serviceWorker' in navigator) {
            navigator.serviceWorker.getRegistrations().then(regs => {
                if (regs.length > 0) {
                    setSwStatus(`Active (${regs.length})`);
                } else {
                    setSwStatus("None Found - Attempting Register...");
                    registerSW();
                }
            });
        } else {
            setSwStatus("Not Supported");
        }

        return () => window.removeEventListener('beforeinstallprompt', handler);
    }, [deferredPrompt]);

    const handleInstall = async () => {
        if (deferredPrompt) {
            deferredPrompt.prompt();
            const { outcome } = await deferredPrompt.userChoice;
            if (outcome === 'accepted') {
                setDeferredPrompt(null);
            }
        } else if (isIOS) {
            setShowIOSPrompt(true);
        }
    };

    if (!deferredPrompt && !isIOS) {
        return (
            <div className="w-full mt-2">
                <button disabled className="w-full py-3 bg-slate-900/50 text-slate-600 font-bold rounded-xl border border-slate-800 flex items-center justify-center gap-2 uppercase tracking-wider cursor-not-allowed">
                    <Download size={18} /> Install Unavailable
                </button>
                <div className="text-[10px] text-slate-600 text-center mt-1 font-mono">
                    Status: {debugStatus}<br />
                    SW: {swStatus}
                </div>
                {swStatus.includes("Error") || swStatus.includes("None") ? (
                    <button onClick={registerSW} className="w-full mt-1 py-1 bg-red-900/30 text-red-400 text-[10px] rounded border border-red-800">
                        FORCE REGISTER SW
                    </button>
                ) : null}

                {/* FORCE UPDATE BUTTON (Cache Buster) */}
                <button
                    onClick={async () => {
                        if ('serviceWorker' in navigator) {
                            const registrations = await navigator.serviceWorker.getRegistrations();
                            for (const registration of registrations) {
                                await registration.unregister();
                            }
                            window.location.reload();
                        }
                    }}
                    className="w-full mt-2 py-2 bg-red-900/20 text-red-500 text-[10px] font-bold uppercase tracking-widest rounded border border-red-900/30 hover:bg-red-900/40 transition-colors"
                >
                    ⚠️ Force Update (Fix v4.1)
                </button>
            </div >
        );
    }

    return (
        <>
            <button
                onClick={handleInstall}
                className="w-full py-3 bg-purple-900/50 hover:bg-purple-800/50 text-purple-200 font-bold rounded-xl border border-purple-500/30 flex items-center justify-center gap-2 uppercase tracking-wider transition-all mt-2"
            >
                <Download size={18} className="animate-bounce" /> {isIOS ? "Install App" : "Install App"}
            </button>

            {showIOSPrompt && (
                <div className="fixed inset-0 z-[300] bg-black/90 backdrop-blur flex items-center justify-center p-6" onClick={() => setShowIOSPrompt(false)}>
                    <div className="bg-slate-900 border border-slate-700 p-6 rounded-2xl max-w-sm text-center relative">
                        <div className="absolute top-4 right-4 text-slate-500"><X size={20} /></div>
                        <h3 className="text-xl font-bold text-white mb-4">Install on iOS</h3>
                        <p className="text-slate-300 mb-4 text-sm">To install this app on your iPhone/iPad:</p>
                        <ol className="text-left text-slate-400 text-sm space-y-3 bg-slate-950 p-4 rounded-xl border border-slate-800">
                            <li className="flex items-center gap-2">1. Tap the <span className="text-blue-400 font-bold">Share</span> button <span className="bg-slate-800 p-1 rounded"><Download size={12} /></span></li>
                            <li className="flex items-center gap-2">2. Scroll down and tap <span className="text-white font-bold">Add to Home Screen</span></li>
                        </ol>
                    </div>
                </div>
            )}
        </>
    );
};
