// Auto-generated by Dev Editor - DO NOT EDIT MANUALLY
// Last updated: ${new Date().toISOString()}

import { Platform, PlatformType } from '../../types';

export const CUSTOM_LEVEL: Platform[] = [
    // Ground platform
    {
        id: 999,
        x: -400,
        y: 100,
        initialX: -400,
        width: 1200,
        height: 50,
        type: PlatformType.STICKY,
        color: '#84cc16',
        broken: false,
        respawnTimer: 0
    }
    // Add more platforms here via editor
];

export const CUSTOM_UI_LAYOUT = {
    scale: 1,
    x: 0,
    y: 0
};
