import React, { useState } from 'react';
import { X, Save, MousePointer2, RotateCcw } from 'lucide-react';
import * as Constants from '../../constants';
import { Platform } from '../../types';
import { UIEditorOverlay } from './UIEditorOverlay';

interface DevEditorProps {
    onClose: () => void;
    controlLayout: { scale: number; x: number; y: number };
    setControlLayout: (layout: { scale: number; x: number; y: number }) => void;
    platformsRef: React.MutableRefObject<Platform[]>;
    config: any;
    onForceUpdate: () => void;
    gameState: any;
    setGameState: React.Dispatch<React.SetStateAction<any>>;
    cameraRef: React.MutableRefObject<{ y: number; targetY: number; shake: number }>;
}

export const DevEditor: React.FC<DevEditorProps> = ({
    onClose,
    controlLayout,
    setControlLayout,
    platformsRef,
    config,
    onForceUpdate,
    gameState,
    setGameState,
    cameraRef
}) => {
    const [activeTab, setActiveTab] = useState<'UI' | 'LEVEL'>('UI');
    const [cameraY, setCameraY] = useState(0);

    const handleSave = () => {
        if (platformsRef.current.length > 0) {
            localStorage.setItem('NEON_TEST_LEVEL', JSON.stringify(platformsRef.current));
            localStorage.setItem('NEON_UI_LAYOUT', JSON.stringify(controlLayout));

            const timestamp = new Date().toISOString();
            const platformsCode = platformsRef.current.map(p => `    {
        id: ${p.id},
        x: ${Math.round(p.x)},
        y: ${Math.round(p.y)},
        initialX: ${Math.round(p.initialX || p.x)},
        width: ${Math.round(p.width)},
        height: ${Math.round(p.height)},
        type: PlatformType.${p.type},
        color: '${p.color}',
        broken: false,
        respawnTimer: 0
    }`).join(',\n');

            const fileContent = `// Auto-generated by Dev Editor
// Last updated: ${timestamp}

import { Platform, PlatformType } from '../../types';

export const CUSTOM_LEVEL: Platform[] = [
${platformsCode}
];

export const CUSTOM_UI_LAYOUT = {
    scale: ${controlLayout.scale},
    x: ${controlLayout.x},
    y: ${controlLayout.y}
};
`;

            const blob = new Blob([fileContent], { type: 'text/typescript' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = 'customConfig.ts';
            a.click();
            URL.revokeObjectURL(url);

            alert('✅ SAVED!\n\n📁 customConfig.ts downloaded\n\n→ Commit to GitHub for global deploy');
        }
    };

    const handleWheel = (e: React.WheelEvent) => {
        if (activeTab === 'LEVEL') {
            e.preventDefault();
            const newY = cameraRef.current.y + e.deltaY;
            cameraRef.current.y = newY;
            cameraRef.current.targetY = newY;
            setCameraY(newY);
        }
    };

    const handleCameraReset = () => {
        cameraRef.current.y = 0;
        cameraRef.current.targetY = 0;
        setCameraY(0);
    };

    return (
        <div
            className="fixed inset-0 flex flex-col font-sans text-white select-none pointer-events-none"
            style={{ zIndex: Constants.Z_LAYERS.OVERLAY + 10 }}
        >
            {/* HEADER */}
            <div className="h-16 bg-slate-900/90 border-b border-cyan-500/30 flex items-center justify-between px-6 backdrop-blur-md shadow-xl pointer-events-auto">
                <div className="flex items-center gap-4">
                    <div className="bg-red-600 text-white text-xs font-black px-2 py-1 rounded">EDITOR</div>
                    <h2 className="text-lg font-bold tracking-wide text-cyan-400">VISUAL DESIGNER</h2>
                </div>

                <div className="flex bg-slate-800/50 rounded-lg p-1 border border-slate-700">
                    <button
                        onClick={() => setActiveTab('UI')}
                        className={`px-6 py-2 rounded-md text-sm font-bold transition-all ${activeTab === 'UI' ? 'bg-cyan-600 text-white shadow-lg' : 'text-slate-400 hover:text-white'}`}
                    >
                        UI LAYOUT
                    </button>
                    <button
                        onClick={() => setActiveTab('LEVEL')}
                        className={`px-6 py-2 rounded-md text-sm font-bold transition-all ${activeTab === 'LEVEL' ? 'bg-purple-600 text-white shadow-lg' : 'text-slate-400 hover:text-white'}`}
                    >
                        LEVEL DESIGN
                    </button>
                </div>

                <div className="flex items-center gap-3">
                    <button
                        onClick={handleSave}
                        className="flex items-center gap-2 bg-green-600 hover:bg-green-500 text-white px-4 py-2 rounded-lg font-bold text-sm transition-all"
                    >
                        <Save size={16} /> SAVE
                    </button>
                    <button
                        onClick={onClose}
                        className="p-2 hover:bg-red-500/20 rounded-full text-slate-400 hover:text-red-400 transition-colors"
                    >
                        <X size={24} />
                    </button>
                </div>
            </div>

            {/* MAIN CONTENT */}
            <div className="flex-1 relative overflow-hidden" onWheel={handleWheel}>
                <UIEditorOverlay isActive={activeTab === 'UI'} />

                {activeTab === 'UI' && (
                    <div className="absolute top-4 left-1/2 transform -translate-x-1/2 bg-black/60 backdrop-blur px-6 py-3 rounded-full border border-cyan-500/30 flex items-center gap-4 shadow-lg pointer-events-auto">
                        <span className="font-bold text-sm">CLICK ELEMENTS TO SELECT & DRAG</span>
                        <div className="h-4 w-px bg-slate-600 mx-2" />
                        <button
                            onClick={() => {
                                const elements = document.querySelectorAll('[style*="position: fixed"]');
                                elements.forEach(el => {
                                    (el as HTMLElement).style.position = '';
                                    (el as HTMLElement).style.left = '';
                                    (el as HTMLElement).style.top = '';
                                });
                                alert('✅ UI Reset!');
                            }}
                            className="px-3 py-1 bg-red-600 hover:bg-red-500 rounded text-xs font-bold flex items-center gap-1"
                        >
                            <RotateCcw size={12} /> RESET
                        </button>
                    </div>
                )}

                {activeTab === 'LEVEL' && (
                    <>
                        <div className="absolute top-4 right-4 bg-black/80 backdrop-blur p-4 rounded-lg border border-purple-500/30 pointer-events-auto">
                            <h3 className="font-bold text-purple-300 mb-2 text-sm">Camera</h3>
                            <div className="flex flex-col gap-2">
                                <div className="text-xs font-mono text-cyan-300">Y: {Math.round(cameraY)}</div>
                                <button onClick={handleCameraReset} className="px-3 py-1 bg-slate-700 hover:bg-slate-600 rounded text-xs font-bold flex items-center gap-1">
                                    <RotateCcw size={12} /> Reset
                                </button>
                                <div className="text-xs text-slate-400">Scroll to pan</div>
                            </div>
                        </div>

                        <div className="absolute top-4 left-4 bg-black/80 backdrop-blur p-4 rounded-lg border border-purple-500/30 max-w-xs pointer-events-auto">
                            <h3 className="font-bold text-purple-300 mb-2 flex items-center gap-2">
                                <MousePointer2 size={16} /> Level Editor
                            </h3>
                            <p className="text-sm text-slate-300 mb-4">
                                Ctrl+Click to add platforms. Scroll to pan camera.
                            </p>

                            <button
                                onClick={() => {
                                    setGameState((prev: any) => ({ ...prev, isEditing: !prev.isEditing }));
                                    onClose();
                                }}
                                className={`w-full py-2 rounded font-bold mb-4 ${gameState.isEditing ? 'bg-red-600 text-white' : 'bg-purple-600 text-white'}`}
                            >
                                {gameState.isEditing ? 'DISABLE EDIT' : 'ENABLE EDIT'}
                            </button>

                            <div className="text-xs text-slate-500">
                                * Enable, edit, then SAVE
                            </div>
                        </div>
                    </>
                )}
            </div>
        </div>
    );
};
