import React, { useState } from 'react';
import { X, Save, MousePointer2, RotateCcw } from 'lucide-react';
import * as Constants from '../../constants';
import { Platform } from '../../types';
import { UIEditorOverlay } from './UIEditorOverlay';

interface DevEditorProps {
    onClose: () => void;
    controlLayout: { scale: number; x: number; y: number };
    setControlLayout: (layout: { scale: number; x: number; y: number }) => void;
    platformsRef: React.MutableRefObject<Platform[]>;
    config: any;
    onForceUpdate: () => void;
    gameState: any;
    setGameState: React.Dispatch<React.SetStateAction<any>>;
    cameraRef: React.MutableRefObject<{ y: number; targetY: number; shake: number }>;
}

export const DevEditor: React.FC<DevEditorProps> = ({
    onClose,
    controlLayout,
    setControlLayout,
    platformsRef,
    config,
    onForceUpdate,
    gameState,
    setGameState,
    cameraRef
}) => {
    const [activeTab, setActiveTab] = useState<'UI' | 'LEVEL'>('UI');
    const [saveStatus, setSaveStatus] = useState<'IDLE' | 'SAVED'>('IDLE');
    const isMobile = typeof window !== 'undefined' && window.innerWidth < 768;

    const handleSave = () => {
        // Save to localStorage
        localStorage.setItem('NEON_TEST_LEVEL', JSON.stringify(platformsRef.current));
        localStorage.setItem('NEON_UI_LAYOUT', JSON.stringify(controlLayout));

        // Generate config file only if there are platforms
        if (platformsRef.current.length > 0) {
            const timestamp = new Date().toISOString();
            const platformsCode = platformsRef.current.map(p => `    {
        id: ${p.id},
        x: ${Math.round(p.x)},
        y: ${Math.round(p.y)},
        initialX: ${Math.round(p.initialX || p.x)},
        width: ${Math.round(p.width)},
        height: ${Math.round(p.height)},
        type: PlatformType.${p.type},
        color: '${p.color}',
        broken: false,
        respawnTimer: 0
    }`).join(',\n');

            const fileContent = `// Auto-generated by Dev Editor
// Last updated: ${timestamp}

import { Platform, PlatformType } from '../../types';

export const CUSTOM_LEVEL: Platform[] = [
${platformsCode}
];

export const CUSTOM_UI_LAYOUT = {
    scale: ${controlLayout.scale},
    x: ${controlLayout.x},
    y: ${controlLayout.y}
};
`;
            // Only download on desktop to avoid mobile issues
            if (!isMobile) {
                const blob = new Blob([fileContent], { type: 'text/typescript' });
                const url = URL.createObjectURL(blob);
                const a = document.createElement('a');
                a.href = url;
                a.download = 'customConfig.ts';
                a.click();
                URL.revokeObjectURL(url);
            }
        }

        setSaveStatus('SAVED');
        setTimeout(() => setSaveStatus('IDLE'), 2000);
    };

    const handleWheel = (e: React.WheelEvent) => {
        if (activeTab === 'LEVEL') {
            e.preventDefault();
            const newY = cameraRef.current.y + e.deltaY;
            cameraRef.current.y = newY;
            cameraRef.current.targetY = newY;
            setCameraY(newY);
        }
    };

    const handleCameraReset = () => {
        cameraRef.current.y = 0;
        cameraRef.current.targetY = 0;
        setCameraY(0);
    };

    return (
        <div
            className="fixed inset-0 flex flex-col font-sans text-white select-none pointer-events-none"
            style={{ zIndex: Constants.Z_LAYERS.OVERLAY + 10 }}
        >
            {/* HEADER - Compact on mobile */}
            <div data-editor-ui className={`bg-slate-900/90 border-b border-cyan-500/30 flex items-center justify-between backdrop-blur-md shadow-xl pointer-events-auto ${isMobile ? 'h-10 px-2' : 'h-16 px-6'}`}>
                <div className="flex items-center gap-2">
                    <div className={`bg-red-600 text-white font-black rounded ${isMobile ? 'text-[8px] px-1 py-0.5' : 'text-xs px-2 py-1'}`}>
                        {isMobile ? 'ED' : 'EDITOR'}
                    </div>
                </div>

                <div className={`flex bg-slate-800/50 rounded-lg border border-slate-700 ${isMobile ? 'p-0.5' : 'p-1'}`}>
                    <button
                        onClick={() => setActiveTab('UI')}
                        className={`rounded-md font-bold transition-all ${isMobile ? 'px-2 py-0.5 text-[9px]' : 'px-6 py-2 text-sm'} ${activeTab === 'UI' ? 'bg-cyan-600 text-white shadow-lg' : 'text-slate-400 hover:text-white'}`}
                    >
                        UI
                    </button>
                    <button
                        onClick={() => setActiveTab('LEVEL')}
                        className={`rounded-md font-bold transition-all ${isMobile ? 'px-2 py-0.5 text-[9px]' : 'px-6 py-2 text-sm'} ${activeTab === 'LEVEL' ? 'bg-purple-600 text-white shadow-lg' : 'text-slate-400 hover:text-white'}`}
                    >
                        LVL
                    </button>
                </div>

                <div className="flex items-center gap-1">
                    <button
                        onClick={handleSave}
                        className={`flex items-center gap-1 rounded-lg font-bold transition-all ${isMobile ? 'px-2 py-0.5 text-[9px]' : 'px-4 py-2 text-sm'} ${saveStatus === 'SAVED' ? 'bg-green-500 text-white' : 'bg-green-600 hover:bg-green-500 text-white'}`}
                    >
                        <Save size={isMobile ? 10 : 16} /> {saveStatus === 'SAVED' ? 'SAVED!' : (isMobile ? '' : 'SAVE')}
                    </button>
                    <button
                        onClick={onClose}
                        className={`hover:bg-red-500/20 rounded-full text-slate-400 hover:text-red-400 transition-colors ${isMobile ? 'p-0.5' : 'p-2'}`}
                    >
                        <X size={isMobile ? 14 : 24} />
                    </button>
                </div>
            </div>

            {/* MAIN CONTENT */}
            <div className="flex-1 relative overflow-hidden" onWheel={handleWheel}>
                <UIEditorOverlay isActive={activeTab === 'UI'} />

                {activeTab === 'UI' && (
                    <div data-editor-ui className={`absolute left-1/2 transform -translate-x-1/2 bg-black/60 backdrop-blur rounded-full border border-cyan-500/30 flex items-center shadow-lg pointer-events-auto ${isMobile ? 'top-1 px-2 py-1 gap-1' : 'top-4 px-6 py-3 gap-4'}`}>
                        <span className={`font-bold ${isMobile ? 'text-[8px]' : 'text-sm'}`}>
                            {isMobile ? 'TAP' : 'CLICK TO SELECT'}
                        </span>
                        <button
                            onClick={() => {
                                const elements = document.querySelectorAll('[style*="position: fixed"]');
                                elements.forEach(el => {
                                    (el as HTMLElement).style.position = '';
                                    (el as HTMLElement).style.left = '';
                                    (el as HTMLElement).style.top = '';
                                });
                                setSaveStatus('SAVED');
                                setTimeout(() => setSaveStatus('IDLE'), 2000);
                            }}
                            className={`bg-red-600 hover:bg-red-500 rounded font-bold flex items-center gap-0.5 ${isMobile ? 'px-1.5 py-0.5 text-[7px]' : 'px-3 py-1 text-xs'}`}
                        >
                            <RotateCcw size={isMobile ? 8 : 12} />
                        </button>
                    </div>
                )}

                {/* MOBILE SAVE BUTTON - Large and visible */}
                {activeTab === 'UI' && isMobile && (
                    <button
                        data-editor-ui
                        onClick={handleSave}
                        className={`absolute bottom-20 right-4 text-white rounded-full shadow-lg pointer-events-auto flex items-center justify-center transition-all ${saveStatus === 'SAVED' ? 'bg-green-500 scale-110' : 'bg-green-600 hover:bg-green-500'}`}
                        style={{
                            width: '56px',
                            height: '56px',
                            zIndex: 100001
                        }}
                    >
                        {saveStatus === 'SAVED' ? <span className="text-[10px] font-bold">OK</span> : <Save size={24} />}
                    </button>
                )}

                {activeTab === 'LEVEL' && (
                    <>
                        <div data-editor-ui className={`absolute right-2 bg-black/80 backdrop-blur rounded-lg border border-purple-500/30 pointer-events-auto ${isMobile ? 'top-1 p-2' : 'top-4 p-4'}`}>
                            <h3 className={`font-bold text-purple-300 mb-1 ${isMobile ? 'text-[9px]' : 'text-sm'}`}>Cam</h3>
                            <div className="flex flex-col gap-1">
                                <div className={`font-mono text-cyan-300 ${isMobile ? 'text-[8px]' : 'text-xs'}`}>Y: {Math.round(cameraY)}</div>
                                <button onClick={handleCameraReset} className={`bg-slate-700 hover:bg-slate-600 rounded font-bold flex items-center gap-0.5 ${isMobile ? 'px-1 py-0.5 text-[7px]' : 'px-3 py-1 text-xs'}`}>
                                    <RotateCcw size={isMobile ? 8 : 12} />
                                </button>
                            </div>
                        </div>

                        <div data-editor-ui className={`absolute left-2 bg-black/80 backdrop-blur rounded-lg border border-purple-500/30 max-w-xs pointer-events-auto ${isMobile ? 'top-1 p-2' : 'top-4 p-4'}`}>
                            <h3 className={`font-bold text-purple-300 mb-1 flex items-center gap-1 ${isMobile ? 'text-[9px]' : 'text-sm'}`}>
                                <MousePointer2 size={isMobile ? 10 : 16} /> {isMobile ? 'Edit' : 'Level Editor'}
                            </h3>
                            <p className={`text-slate-300 mb-2 ${isMobile ? 'text-[8px]' : 'text-sm'}`}>
                                {isMobile ? 'Ctrl+Click' : 'Ctrl+Click to add platforms'}
                            </p>

                            <button
                                onClick={() => {
                                    setGameState((prev: any) => ({ ...prev, isEditing: !prev.isEditing }));
                                    onClose();
                                }}
                                className={`w-full rounded font-bold ${isMobile ? 'py-1 text-[8px]' : 'py-2 text-sm'} ${gameState.isEditing ? 'bg-red-600 text-white' : 'bg-purple-600 text-white'}`}
                            >
                                {gameState.isEditing ? 'DISABLE' : 'ENABLE'}
                            </button>
                        </div>
                    </>
                )}
            </div>
        </div>
    );
};
